/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchGraphDto
 */
export interface BranchGraphDto {
    /**
     * 
     * @type {number}
     * @memberof BranchGraphDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BranchGraphDto
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof BranchGraphDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof BranchGraphDto
     */
    fromCommitId?: number;
    /**
     * 
     * @type {number}
     * @memberof BranchGraphDto
     */
    rootCommitId?: number;
    /**
     * 
     * @type {number}
     * @memberof BranchGraphDto
     */
    leafCommitId?: number;
    /**
     * 
     * @type {number}
     * @memberof BranchGraphDto
     */
    saveId?: number;
}

/**
 * Check if a given object implements the BranchGraphDto interface.
 */
export function instanceOfBranchGraphDto(value: object): value is BranchGraphDto {
    return true;
}

export function BranchGraphDtoFromJSON(json: any): BranchGraphDto {
    return BranchGraphDtoFromJSONTyped(json, false);
}

export function BranchGraphDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchGraphDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'fromCommitId': json['fromCommitId'] == null ? undefined : json['fromCommitId'],
        'rootCommitId': json['rootCommitId'] == null ? undefined : json['rootCommitId'],
        'leafCommitId': json['leafCommitId'] == null ? undefined : json['leafCommitId'],
        'saveId': json['saveId'] == null ? undefined : json['saveId'],
    };
}

export function BranchGraphDtoToJSON(json: any): BranchGraphDto {
    return BranchGraphDtoToJSONTyped(json, false);
}

export function BranchGraphDtoToJSONTyped(value?: BranchGraphDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'fromCommitId': value['fromCommitId'],
        'rootCommitId': value['rootCommitId'],
        'leafCommitId': value['leafCommitId'],
        'saveId': value['saveId'],
    };
}

