/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompareMergeResponse
 */
export interface CompareMergeResponse {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CompareMergeResponse
     */
    base?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CompareMergeResponse
     */
    target?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the CompareMergeResponse interface.
 */
export function instanceOfCompareMergeResponse(value: object): value is CompareMergeResponse {
    return true;
}

export function CompareMergeResponseFromJSON(json: any): CompareMergeResponse {
    return CompareMergeResponseFromJSONTyped(json, false);
}

export function CompareMergeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompareMergeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'] == null ? undefined : json['base'],
        'target': json['target'] == null ? undefined : json['target'],
    };
}

export function CompareMergeResponseToJSON(json: any): CompareMergeResponse {
    return CompareMergeResponseToJSONTyped(json, false);
}

export function CompareMergeResponseToJSONTyped(value?: CompareMergeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'target': value['target'],
    };
}

