/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitGraphDto } from './CommitGraphDto';
import {
    CommitGraphDtoFromJSON,
    CommitGraphDtoFromJSONTyped,
    CommitGraphDtoToJSON,
    CommitGraphDtoToJSONTyped,
} from './CommitGraphDto';
import type { BranchGraphDto } from './BranchGraphDto';
import {
    BranchGraphDtoFromJSON,
    BranchGraphDtoFromJSONTyped,
    BranchGraphDtoToJSON,
    BranchGraphDtoToJSONTyped,
} from './BranchGraphDto';
import type { EdgeDto } from './EdgeDto';
import {
    EdgeDtoFromJSON,
    EdgeDtoFromJSONTyped,
    EdgeDtoToJSON,
    EdgeDtoToJSONTyped,
} from './EdgeDto';

/**
 * 
 * @export
 * @interface GraphResponse
 */
export interface GraphResponse {
    /**
     * 
     * @type {string}
     * @memberof GraphResponse
     */
    title?: string;
    /**
     * 
     * @type {Array<CommitGraphDto>}
     * @memberof GraphResponse
     */
    commits?: Array<CommitGraphDto>;
    /**
     * 
     * @type {Array<EdgeDto>}
     * @memberof GraphResponse
     */
    edges?: Array<EdgeDto>;
    /**
     * 
     * @type {Array<BranchGraphDto>}
     * @memberof GraphResponse
     */
    branches?: Array<BranchGraphDto>;
}

/**
 * Check if a given object implements the GraphResponse interface.
 */
export function instanceOfGraphResponse(value: object): value is GraphResponse {
    return true;
}

export function GraphResponseFromJSON(json: any): GraphResponse {
    return GraphResponseFromJSONTyped(json, false);
}

export function GraphResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'commits': json['commits'] == null ? undefined : ((json['commits'] as Array<any>).map(CommitGraphDtoFromJSON)),
        'edges': json['edges'] == null ? undefined : ((json['edges'] as Array<any>).map(EdgeDtoFromJSON)),
        'branches': json['branches'] == null ? undefined : ((json['branches'] as Array<any>).map(BranchGraphDtoFromJSON)),
    };
}

export function GraphResponseToJSON(json: any): GraphResponse {
    return GraphResponseToJSONTyped(json, false);
}

export function GraphResponseToJSONTyped(value?: GraphResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'commits': value['commits'] == null ? undefined : ((value['commits'] as Array<any>).map(CommitGraphDtoToJSON)),
        'edges': value['edges'] == null ? undefined : ((value['edges'] as Array<any>).map(EdgeDtoToJSON)),
        'branches': value['branches'] == null ? undefined : ((value['branches'] as Array<any>).map(BranchGraphDtoToJSON)),
    };
}

