/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 이미지 업로드 완료 응답
 * @export
 * @interface ImageUploadCompleteResponse
 */
export interface ImageUploadCompleteResponse {
    /**
     * 이미지 id
     * @type {number}
     * @memberof ImageUploadCompleteResponse
     */
    imageId?: number;
    /**
     * S3 object key
     * @type {string}
     * @memberof ImageUploadCompleteResponse
     */
    objectKey?: string;
    /**
     * CloudFront 또는 CDN 이미지 URL
     * @type {string}
     * @memberof ImageUploadCompleteResponse
     */
    imageUrl?: string;
    /**
     * 검증된 이미지 Content-Type
     * @type {string}
     * @memberof ImageUploadCompleteResponse
     */
    contentType?: string;
    /**
     * 검증된 파일 크기(byte)
     * @type {number}
     * @memberof ImageUploadCompleteResponse
     */
    size?: number;
    /**
     * 이미지 상태
     * @type {string}
     * @memberof ImageUploadCompleteResponse
     */
    status?: ImageUploadCompleteResponseStatusEnum;
}


/**
 * @export
 */
export const ImageUploadCompleteResponseStatusEnum = {
    Pending: 'PENDING',
    Active: 'ACTIVE',
    Failed: 'FAILED'
} as const;
export type ImageUploadCompleteResponseStatusEnum = typeof ImageUploadCompleteResponseStatusEnum[keyof typeof ImageUploadCompleteResponseStatusEnum];


/**
 * Check if a given object implements the ImageUploadCompleteResponse interface.
 */
export function instanceOfImageUploadCompleteResponse(value: object): value is ImageUploadCompleteResponse {
    return true;
}

export function ImageUploadCompleteResponseFromJSON(json: any): ImageUploadCompleteResponse {
    return ImageUploadCompleteResponseFromJSONTyped(json, false);
}

export function ImageUploadCompleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageUploadCompleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'objectKey': json['objectKey'] == null ? undefined : json['objectKey'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'size': json['size'] == null ? undefined : json['size'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ImageUploadCompleteResponseToJSON(json: any): ImageUploadCompleteResponse {
    return ImageUploadCompleteResponseToJSONTyped(json, false);
}

export function ImageUploadCompleteResponseToJSONTyped(value?: ImageUploadCompleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageId': value['imageId'],
        'objectKey': value['objectKey'],
        'imageUrl': value['imageUrl'],
        'contentType': value['contentType'],
        'size': value['size'],
        'status': value['status'],
    };
}

