/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 이미지 업로드 URL 발급 응답
 * @export
 * @interface ImageUploadUrlResponse
 */
export interface ImageUploadUrlResponse {
    /**
     * 생성된 이미지 메타데이터 id
     * @type {number}
     * @memberof ImageUploadUrlResponse
     */
    imageId?: number;
    /**
     * S3 object key
     * @type {string}
     * @memberof ImageUploadUrlResponse
     */
    objectKey?: string;
    /**
     * 클라이언트가 PUT 요청을 보낼 presigned URL
     * @type {string}
     * @memberof ImageUploadUrlResponse
     */
    uploadUrl?: string;
    /**
     * 업로드에 사용할 HTTP method
     * @type {string}
     * @memberof ImageUploadUrlResponse
     */
    method?: string;
    /**
     * URL 만료 시간(초)
     * @type {number}
     * @memberof ImageUploadUrlResponse
     */
    expiresInSeconds?: number;
}

/**
 * Check if a given object implements the ImageUploadUrlResponse interface.
 */
export function instanceOfImageUploadUrlResponse(value: object): value is ImageUploadUrlResponse {
    return true;
}

export function ImageUploadUrlResponseFromJSON(json: any): ImageUploadUrlResponse {
    return ImageUploadUrlResponseFromJSONTyped(json, false);
}

export function ImageUploadUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageUploadUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'objectKey': json['objectKey'] == null ? undefined : json['objectKey'],
        'uploadUrl': json['uploadUrl'] == null ? undefined : json['uploadUrl'],
        'method': json['method'] == null ? undefined : json['method'],
        'expiresInSeconds': json['expiresInSeconds'] == null ? undefined : json['expiresInSeconds'],
    };
}

export function ImageUploadUrlResponseToJSON(json: any): ImageUploadUrlResponse {
    return ImageUploadUrlResponseToJSONTyped(json, false);
}

export function ImageUploadUrlResponseToJSONTyped(value?: ImageUploadUrlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageId': value['imageId'],
        'objectKey': value['objectKey'],
        'uploadUrl': value['uploadUrl'],
        'method': value['method'],
        'expiresInSeconds': value['expiresInSeconds'],
    };
}

