/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 이미지 업로드 URL 발급 요청
 * @export
 * @interface ImageUploadUrlRequest
 */
export interface ImageUploadUrlRequest {
    /**
     * 이미지가 연결될 문서 id
     * @type {number}
     * @memberof ImageUploadUrlRequest
     */
    docId: number;
    /**
     * 원본 파일명
     * @type {string}
     * @memberof ImageUploadUrlRequest
     */
    originalFileName: string;
    /**
     * 이미지 Content-Type
     * @type {string}
     * @memberof ImageUploadUrlRequest
     */
    contentType: string;
    /**
     * 파일 크기(byte)
     * @type {number}
     * @memberof ImageUploadUrlRequest
     */
    size: number;
}

/**
 * Check if a given object implements the ImageUploadUrlRequest interface.
 */
export function instanceOfImageUploadUrlRequest(value: object): value is ImageUploadUrlRequest {
    if (!('docId' in value) || value['docId'] === undefined) return false;
    if (!('originalFileName' in value) || value['originalFileName'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function ImageUploadUrlRequestFromJSON(json: any): ImageUploadUrlRequest {
    return ImageUploadUrlRequestFromJSONTyped(json, false);
}

export function ImageUploadUrlRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageUploadUrlRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'docId': json['docId'],
        'originalFileName': json['originalFileName'],
        'contentType': json['contentType'],
        'size': json['size'],
    };
}

export function ImageUploadUrlRequestToJSON(json: any): ImageUploadUrlRequest {
    return ImageUploadUrlRequestToJSONTyped(json, false);
}

export function ImageUploadUrlRequestToJSONTyped(value?: ImageUploadUrlRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'docId': value['docId'],
        'originalFileName': value['originalFileName'],
        'contentType': value['contentType'],
        'size': value['size'],
    };
}

