/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MergeResponse
 */
export interface MergeResponse {
    /**
     * 
     * @type {number}
     * @memberof MergeResponse
     */
    branchId?: number;
    /**
     * 
     * @type {number}
     * @memberof MergeResponse
     */
    saveId?: number;
}

/**
 * Check if a given object implements the MergeResponse interface.
 */
export function instanceOfMergeResponse(value: object): value is MergeResponse {
    return true;
}

export function MergeResponseFromJSON(json: any): MergeResponse {
    return MergeResponseFromJSONTyped(json, false);
}

export function MergeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'branchId': json['branchId'] == null ? undefined : json['branchId'],
        'saveId': json['saveId'] == null ? undefined : json['saveId'],
    };
}

export function MergeResponseToJSON(json: any): MergeResponse {
    return MergeResponseToJSONTyped(json, false);
}

export function MergeResponseToJSONTyped(value?: MergeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branchId': value['branchId'],
        'saveId': value['saveId'],
    };
}

