/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MergeRequest
 */
export interface MergeRequest {
    /**
     * 
     * @type {string}
     * @memberof MergeRequest
     */
    branchName: string;
    /**
     * 
     * @type {number}
     * @memberof MergeRequest
     */
    baseCommitId: number;
    /**
     * 
     * @type {number}
     * @memberof MergeRequest
     */
    targetCommitId: number;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof MergeRequest
     */
    content?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the MergeRequest interface.
 */
export function instanceOfMergeRequest(value: object): value is MergeRequest {
    if (!('branchName' in value) || value['branchName'] === undefined) return false;
    if (!('baseCommitId' in value) || value['baseCommitId'] === undefined) return false;
    if (!('targetCommitId' in value) || value['targetCommitId'] === undefined) return false;
    return true;
}

export function MergeRequestFromJSON(json: any): MergeRequest {
    return MergeRequestFromJSONTyped(json, false);
}

export function MergeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'branchName': json['branchName'],
        'baseCommitId': json['baseCommitId'],
        'targetCommitId': json['targetCommitId'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function MergeRequestToJSON(json: any): MergeRequest {
    return MergeRequestToJSONTyped(json, false);
}

export function MergeRequestToJSONTyped(value?: MergeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branchName': value['branchName'],
        'baseCommitId': value['baseCommitId'],
        'targetCommitId': value['targetCommitId'],
        'content': value['content'],
    };
}

