/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThumbnailSyncResponse } from './ThumbnailSyncResponse';
import {
    ThumbnailSyncResponseFromJSON,
    ThumbnailSyncResponseFromJSONTyped,
    ThumbnailSyncResponseToJSON,
    ThumbnailSyncResponseToJSONTyped,
} from './ThumbnailSyncResponse';

/**
 * 저장 수정 응답
 * @export
 * @interface SaveUpdateResponse
 */
export interface SaveUpdateResponse {
    /**
     * 저장 수정 시각
     * @type {Date}
     * @memberof SaveUpdateResponse
     */
    updatedAt?: Date;
    /**
     * 프론트 썸네일 동기화 판단에 필요한 정보
     * @type {ThumbnailSyncResponse}
     * @memberof SaveUpdateResponse
     */
    thumbnail?: ThumbnailSyncResponse;
}

/**
 * Check if a given object implements the SaveUpdateResponse interface.
 */
export function instanceOfSaveUpdateResponse(value: object): value is SaveUpdateResponse {
    return true;
}

export function SaveUpdateResponseFromJSON(json: any): SaveUpdateResponse {
    return SaveUpdateResponseFromJSONTyped(json, false);
}

export function SaveUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'thumbnail': json['thumbnail'] == null ? undefined : ThumbnailSyncResponseFromJSON(json['thumbnail']),
    };
}

export function SaveUpdateResponseToJSON(json: any): SaveUpdateResponse {
    return SaveUpdateResponseToJSONTyped(json, false);
}

export function SaveUpdateResponseToJSONTyped(value?: SaveUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'thumbnail': ThumbnailSyncResponseToJSON(value['thumbnail']),
    };
}

