/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 문서 대표 썸네일 응답
 * @export
 * @interface ThumbnailResponse
 */
export interface ThumbnailResponse {
    /**
     * 대표 썸네일 이미지 id
     * @type {number}
     * @memberof ThumbnailResponse
     */
    imageId?: number;
    /**
     * 대표 썸네일 CDN URL
     * @type {string}
     * @memberof ThumbnailResponse
     */
    thumbnailUrl?: string;
    /**
     * 썸네일 상태(EMPTY/PENDING/READY/FAILED)
     * @type {string}
     * @memberof ThumbnailResponse
     */
    status?: ThumbnailResponseStatusEnum;
    /**
     * 대표 썸네일이 반영한 프론트 상단 영역 signature
     * @type {string}
     * @memberof ThumbnailResponse
     */
    signature?: string;
}


/**
 * @export
 */
export const ThumbnailResponseStatusEnum = {
    Empty: 'EMPTY',
    Pending: 'PENDING',
    Ready: 'READY',
    Failed: 'FAILED'
} as const;
export type ThumbnailResponseStatusEnum = typeof ThumbnailResponseStatusEnum[keyof typeof ThumbnailResponseStatusEnum];


/**
 * Check if a given object implements the ThumbnailResponse interface.
 */
export function instanceOfThumbnailResponse(value: object): value is ThumbnailResponse {
    return true;
}

export function ThumbnailResponseFromJSON(json: any): ThumbnailResponse {
    return ThumbnailResponseFromJSONTyped(json, false);
}

export function ThumbnailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThumbnailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'status': json['status'] == null ? undefined : json['status'],
        'signature': json['signature'] == null ? undefined : json['signature'],
    };
}

export function ThumbnailResponseToJSON(json: any): ThumbnailResponse {
    return ThumbnailResponseToJSONTyped(json, false);
}

export function ThumbnailResponseToJSONTyped(value?: ThumbnailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageId': value['imageId'],
        'thumbnailUrl': value['thumbnailUrl'],
        'status': value['status'],
        'signature': value['signature'],
    };
}

