/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 문서 대표 썸네일 확정 요청
 * @export
 * @interface ThumbnailFinalizeRequest
 */
export interface ThumbnailFinalizeRequest {
    /**
     * 대표 썸네일로 확정할 이미지 id
     * @type {number}
     * @memberof ThumbnailFinalizeRequest
     */
    imageId: number;
    /**
     * 저장 API 응답으로 받은 최신 썸네일 요청 토큰
     * @type {number}
     * @memberof ThumbnailFinalizeRequest
     */
    requestToken: number;
    /**
     * 프론트가 썸네일 캡처 대상 영역 기준으로 계산한 signature
     * @type {string}
     * @memberof ThumbnailFinalizeRequest
     */
    signature: string;
}

/**
 * Check if a given object implements the ThumbnailFinalizeRequest interface.
 */
export function instanceOfThumbnailFinalizeRequest(value: object): value is ThumbnailFinalizeRequest {
    if (!('imageId' in value) || value['imageId'] === undefined) return false;
    if (!('requestToken' in value) || value['requestToken'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function ThumbnailFinalizeRequestFromJSON(json: any): ThumbnailFinalizeRequest {
    return ThumbnailFinalizeRequestFromJSONTyped(json, false);
}

export function ThumbnailFinalizeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThumbnailFinalizeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'imageId': json['imageId'],
        'requestToken': json['requestToken'],
        'signature': json['signature'],
    };
}

export function ThumbnailFinalizeRequestToJSON(json: any): ThumbnailFinalizeRequest {
    return ThumbnailFinalizeRequestToJSONTyped(json, false);
}

export function ThumbnailFinalizeRequestToJSONTyped(value?: ThumbnailFinalizeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageId': value['imageId'],
        'requestToken': value['requestToken'],
        'signature': value['signature'],
    };
}

