/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 저장 후 썸네일 동기화 정보
 * @export
 * @interface ThumbnailSyncResponse
 */
export interface ThumbnailSyncResponse {
    /**
     * 최신 썸네일 요청 토큰. finalize 시 그대로 전달해야 합니다.
     * @type {number}
     * @memberof ThumbnailSyncResponse
     */
    requestToken?: number;
    /**
     * 현재 대표 썸네일이 반영한 signature. 프론트가 계산한 signature와 같으면 업로드를 생략합니다.
     * @type {string}
     * @memberof ThumbnailSyncResponse
     */
    signature?: string;
    /**
     * 썸네일 상태(EMPTY/PENDING/READY/FAILED)
     * @type {string}
     * @memberof ThumbnailSyncResponse
     */
    status?: ThumbnailSyncResponseStatusEnum;
}


/**
 * @export
 */
export const ThumbnailSyncResponseStatusEnum = {
    Empty: 'EMPTY',
    Pending: 'PENDING',
    Ready: 'READY',
    Failed: 'FAILED'
} as const;
export type ThumbnailSyncResponseStatusEnum = typeof ThumbnailSyncResponseStatusEnum[keyof typeof ThumbnailSyncResponseStatusEnum];


/**
 * Check if a given object implements the ThumbnailSyncResponse interface.
 */
export function instanceOfThumbnailSyncResponse(value: object): value is ThumbnailSyncResponse {
    return true;
}

export function ThumbnailSyncResponseFromJSON(json: any): ThumbnailSyncResponse {
    return ThumbnailSyncResponseFromJSONTyped(json, false);
}

export function ThumbnailSyncResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThumbnailSyncResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requestToken': json['requestToken'] == null ? undefined : json['requestToken'],
        'signature': json['signature'] == null ? undefined : json['signature'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ThumbnailSyncResponseToJSON(json: any): ThumbnailSyncResponse {
    return ThumbnailSyncResponseToJSONTyped(json, false);
}

export function ThumbnailSyncResponseToJSONTyped(value?: ThumbnailSyncResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestToken': value['requestToken'],
        'signature': value['signature'],
        'status': value['status'],
    };
}

