/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BranchCreateRequest,
  BranchCreateResponse,
  BranchRenameRequest,
  BranchRenameResponse,
  ErrorResponse,
} from '../models/index';
import {
    BranchCreateRequestFromJSON,
    BranchCreateRequestToJSON,
    BranchCreateResponseFromJSON,
    BranchCreateResponseToJSON,
    BranchRenameRequestFromJSON,
    BranchRenameRequestToJSON,
    BranchRenameResponseFromJSON,
    BranchRenameResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface CreateBranchRequest {
    documentId: number;
    branchCreateRequest: BranchCreateRequest;
}

export interface DeleteBranchRequest {
    branchId: number;
    documentId: number;
}

export interface RenameBranchRequest {
    branchId: number;
    documentId: number;
    branchRenameRequest: BranchRenameRequest;
}

/**
 * 
 */
export class BranchAPIApi extends runtime.BaseAPI {

    /**
     * 선택한 기록(fromCommitId)을 기준으로 새로운 브랜치와 작업장(save)을 생성합니다. 🔐 이 API는 세션 로그인 상태에서 호출되어야 하며, 클라이언트는 쿠키(`JSESSIONID`)를 통해 인증 정보를 전송해야 합니다. 
     * 새 브랜치를 생성합니다.
     */
    async createBranchRaw(requestParameters: CreateBranchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BranchCreateResponse>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling createBranch().'
            );
        }

        if (requestParameters['branchCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'branchCreateRequest',
                'Required parameter "branchCreateRequest" was null or undefined when calling createBranch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/document/{documentId}/branch`;
        urlPath = urlPath.replace(`{${"documentId"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BranchCreateRequestToJSON(requestParameters['branchCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BranchCreateResponseFromJSON(jsonValue));
    }

    /**
     * 선택한 기록(fromCommitId)을 기준으로 새로운 브랜치와 작업장(save)을 생성합니다. 🔐 이 API는 세션 로그인 상태에서 호출되어야 하며, 클라이언트는 쿠키(`JSESSIONID`)를 통해 인증 정보를 전송해야 합니다. 
     * 새 브랜치를 생성합니다.
     */
    async createBranch(requestParameters: CreateBranchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BranchCreateResponse> {
        const response = await this.createBranchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 버전을 삭제합니다. 삭제 조건은 아래와 같습니다:  - 메인 버전(`fromCommit == null`)는 삭제 불가 - 다른 버전이 이 버전을 기반(fromCommit)으로 만들어졌다면 삭제 불가 - 블록, 시퀀스, 저장(MongoDB)도 함께 삭제됨 
     * 버전 삭제
     */
    async deleteBranchRaw(requestParameters: DeleteBranchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['branchId'] == null) {
            throw new runtime.RequiredError(
                'branchId',
                'Required parameter "branchId" was null or undefined when calling deleteBranch().'
            );
        }

        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling deleteBranch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/document/{documentId}/branch/{branchId}`;
        urlPath = urlPath.replace(`{${"branchId"}}`, encodeURIComponent(String(requestParameters['branchId'])));
        urlPath = urlPath.replace(`{${"documentId"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 버전을 삭제합니다. 삭제 조건은 아래와 같습니다:  - 메인 버전(`fromCommit == null`)는 삭제 불가 - 다른 버전이 이 버전을 기반(fromCommit)으로 만들어졌다면 삭제 불가 - 블록, 시퀀스, 저장(MongoDB)도 함께 삭제됨 
     * 버전 삭제
     */
    async deleteBranch(requestParameters: DeleteBranchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBranchRaw(requestParameters, initOverrides);
    }

    /**
     * 버전의 이름을 수정합니다. 메인버전의 이름은 수정할 수 없습니다.
     * 버전 이름 변경
     */
    async renameBranchRaw(requestParameters: RenameBranchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BranchRenameResponse>> {
        if (requestParameters['branchId'] == null) {
            throw new runtime.RequiredError(
                'branchId',
                'Required parameter "branchId" was null or undefined when calling renameBranch().'
            );
        }

        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling renameBranch().'
            );
        }

        if (requestParameters['branchRenameRequest'] == null) {
            throw new runtime.RequiredError(
                'branchRenameRequest',
                'Required parameter "branchRenameRequest" was null or undefined when calling renameBranch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/document/{documentId}/branch/{branchId}`;
        urlPath = urlPath.replace(`{${"branchId"}}`, encodeURIComponent(String(requestParameters['branchId'])));
        urlPath = urlPath.replace(`{${"documentId"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BranchRenameRequestToJSON(requestParameters['branchRenameRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BranchRenameResponseFromJSON(jsonValue));
    }

    /**
     * 버전의 이름을 수정합니다. 메인버전의 이름은 수정할 수 없습니다.
     * 버전 이름 변경
     */
    async renameBranch(requestParameters: RenameBranchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BranchRenameResponse> {
        const response = await this.renameBranchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
