/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ImageUploadCompleteResponse,
  ImageUploadUrlRequest,
  ImageUploadUrlResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ImageUploadCompleteResponseFromJSON,
    ImageUploadCompleteResponseToJSON,
    ImageUploadUrlRequestFromJSON,
    ImageUploadUrlRequestToJSON,
    ImageUploadUrlResponseFromJSON,
    ImageUploadUrlResponseToJSON,
} from '../models/index';

export interface CompleteRequest {
    imageId: number;
}

export interface CreateUploadUrlRequest {
    imageUploadUrlRequest: ImageUploadUrlRequest;
}

/**
 * 
 */
export class ImageAPIApi extends runtime.BaseAPI {

    /**
     * presigned URL로 S3 업로드가 끝난 뒤 호출합니다. 서버는 S3 `HeadObject`로 실제 업로드된 객체를 검증한 뒤 이미지를 `ACTIVE` 상태로 전환합니다. 아직 업로드되지 않았거나 업로드가 실패한 경우 `IMAGE_UPLOAD_NOT_COMPLETED`를 반환합니다. 🔐 이 API는 세션 로그인 상태에서 호출되어야 하며, 클라이언트는 쿠키(`JSESSIONID`)를 통해 인증 정보를 전송해야 합니다. 
     * 이미지 업로드 완료 처리
     */
    async completeRaw(requestParameters: CompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageUploadCompleteResponse>> {
        if (requestParameters['imageId'] == null) {
            throw new runtime.RequiredError(
                'imageId',
                'Required parameter "imageId" was null or undefined when calling complete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/images/{imageId}/complete`;
        urlPath = urlPath.replace(`{${"imageId"}}`, encodeURIComponent(String(requestParameters['imageId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageUploadCompleteResponseFromJSON(jsonValue));
    }

    /**
     * presigned URL로 S3 업로드가 끝난 뒤 호출합니다. 서버는 S3 `HeadObject`로 실제 업로드된 객체를 검증한 뒤 이미지를 `ACTIVE` 상태로 전환합니다. 아직 업로드되지 않았거나 업로드가 실패한 경우 `IMAGE_UPLOAD_NOT_COMPLETED`를 반환합니다. 🔐 이 API는 세션 로그인 상태에서 호출되어야 하며, 클라이언트는 쿠키(`JSESSIONID`)를 통해 인증 정보를 전송해야 합니다. 
     * 이미지 업로드 완료 처리
     */
    async complete(requestParameters: CompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageUploadCompleteResponse> {
        const response = await this.completeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 문서에 업로드할 이미지의 presigned PUT URL을 발급합니다. 응답으로 받은 `uploadUrl`에 클라이언트가 직접 PUT 업로드를 수행한 뒤 `POST /api/images/{imageId}/complete` API를 호출해야 업로드가 완료됩니다. 🔐 이 API는 세션 로그인 상태에서 호출되어야 하며, 클라이언트는 쿠키(`JSESSIONID`)를 통해 인증 정보를 전송해야 합니다. 
     * 이미지 업로드용 Presigned URL 발급
     */
    async createUploadUrlRaw(requestParameters: CreateUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageUploadUrlResponse>> {
        if (requestParameters['imageUploadUrlRequest'] == null) {
            throw new runtime.RequiredError(
                'imageUploadUrlRequest',
                'Required parameter "imageUploadUrlRequest" was null or undefined when calling createUploadUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/images/upload-url`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImageUploadUrlRequestToJSON(requestParameters['imageUploadUrlRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageUploadUrlResponseFromJSON(jsonValue));
    }

    /**
     * 문서에 업로드할 이미지의 presigned PUT URL을 발급합니다. 응답으로 받은 `uploadUrl`에 클라이언트가 직접 PUT 업로드를 수행한 뒤 `POST /api/images/{imageId}/complete` API를 호출해야 업로드가 완료됩니다. 🔐 이 API는 세션 로그인 상태에서 호출되어야 하며, 클라이언트는 쿠키(`JSESSIONID`)를 통해 인증 정보를 전송해야 합니다. 
     * 이미지 업로드용 Presigned URL 발급
     */
    async createUploadUrl(requestParameters: CreateUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageUploadUrlResponse> {
        const response = await this.createUploadUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
