/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  MergeRequest,
  MergeResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    MergeRequestFromJSON,
    MergeRequestToJSON,
    MergeResponseFromJSON,
    MergeResponseToJSON,
} from '../models/index';

export interface MergeOperationRequest {
    docId: number;
    mergeRequest: MergeRequest;
}

/**
 * 
 */
export class MergeAPIApi extends runtime.BaseAPI {

    /**
     * 유저가 소유한 문서에서 기준 커밋과 비교 커밋을 검토한 뒤, 병합 결과를 담은 새 브랜치와 작업장을 생성합니다. 🔐 이 API는 세션 로그인 상태에서 호출되어야 하며, 클라이언트는 쿠키(`JSESSIONID`)를 통해 인증 정보를 전송해야 합니다. 
     * 기준/비교 커밋을 바탕으로 병합 결과 브랜치와 작업장을 생성합니다.
     */
    async mergeRaw(requestParameters: MergeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MergeResponse>> {
        if (requestParameters['docId'] == null) {
            throw new runtime.RequiredError(
                'docId',
                'Required parameter "docId" was null or undefined when calling merge().'
            );
        }

        if (requestParameters['mergeRequest'] == null) {
            throw new runtime.RequiredError(
                'mergeRequest',
                'Required parameter "mergeRequest" was null or undefined when calling merge().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/document/{docId}/merge`;
        urlPath = urlPath.replace(`{${"docId"}}`, encodeURIComponent(String(requestParameters['docId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MergeRequestToJSON(requestParameters['mergeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MergeResponseFromJSON(jsonValue));
    }

    /**
     * 유저가 소유한 문서에서 기준 커밋과 비교 커밋을 검토한 뒤, 병합 결과를 담은 새 브랜치와 작업장을 생성합니다. 🔐 이 API는 세션 로그인 상태에서 호출되어야 하며, 클라이언트는 쿠키(`JSESSIONID`)를 통해 인증 정보를 전송해야 합니다. 
     * 기준/비교 커밋을 바탕으로 병합 결과 브랜치와 작업장을 생성합니다.
     */
    async merge(requestParameters: MergeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MergeResponse> {
        const response = await this.mergeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
