/* tslint:disable */
/* eslint-disable */
/**
 * Docsa API
 * Docsa의 백엔드 API 명세입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ThumbnailFinalizeRequest,
  ThumbnailResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ThumbnailFinalizeRequestFromJSON,
    ThumbnailFinalizeRequestToJSON,
    ThumbnailResponseFromJSON,
    ThumbnailResponseToJSON,
} from '../models/index';

export interface FinalizeThumbnailRequest {
    docId: number;
    thumbnailFinalizeRequest: ThumbnailFinalizeRequest;
}

/**
 * 
 */
export class ThumbnailAPIApi extends runtime.BaseAPI {

    /**
     * 프론트가 생성한 썸네일 이미지를 문서의 대표 썸네일로 확정합니다. 저장 API 응답의 `thumbnail.requestToken`과 프론트가 계산한 `signature`를 함께 전송해야 합니다. 서버는 requestToken을 검증해 오래된 업로드 결과가 최신 썸네일을 덮어쓰지 못하게 막습니다. 확정하려는 이미지는 같은 문서에 연결된 `DOC_THUMBNAIL` 목적의 `ACTIVE` 이미지여야 합니다. 🔐 이 API는 세션 로그인 상태에서 호출되어야 하며, 클라이언트는 쿠키(`JSESSIONID`)를 통해 인증 정보를 전송해야 합니다. 
     * 문서 대표 썸네일 확정
     */
    async finalizeThumbnailRaw(requestParameters: FinalizeThumbnailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThumbnailResponse>> {
        if (requestParameters['docId'] == null) {
            throw new runtime.RequiredError(
                'docId',
                'Required parameter "docId" was null or undefined when calling finalizeThumbnail().'
            );
        }

        if (requestParameters['thumbnailFinalizeRequest'] == null) {
            throw new runtime.RequiredError(
                'thumbnailFinalizeRequest',
                'Required parameter "thumbnailFinalizeRequest" was null or undefined when calling finalizeThumbnail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/document/{docId}/thumbnail`;
        urlPath = urlPath.replace(`{${"docId"}}`, encodeURIComponent(String(requestParameters['docId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ThumbnailFinalizeRequestToJSON(requestParameters['thumbnailFinalizeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThumbnailResponseFromJSON(jsonValue));
    }

    /**
     * 프론트가 생성한 썸네일 이미지를 문서의 대표 썸네일로 확정합니다. 저장 API 응답의 `thumbnail.requestToken`과 프론트가 계산한 `signature`를 함께 전송해야 합니다. 서버는 requestToken을 검증해 오래된 업로드 결과가 최신 썸네일을 덮어쓰지 못하게 막습니다. 확정하려는 이미지는 같은 문서에 연결된 `DOC_THUMBNAIL` 목적의 `ACTIVE` 이미지여야 합니다. 🔐 이 API는 세션 로그인 상태에서 호출되어야 하며, 클라이언트는 쿠키(`JSESSIONID`)를 통해 인증 정보를 전송해야 합니다. 
     * 문서 대표 썸네일 확정
     */
    async finalizeThumbnail(requestParameters: FinalizeThumbnailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThumbnailResponse> {
        const response = await this.finalizeThumbnailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
